
// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  "https://uaejwbglfmvdetvevygn.supabase.co",
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhZWp3YmdsZm12ZGV0dmV2eWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTQ4NzYsImV4cCI6MjA2NDY5MDg3Nn0.gxk4Py0KRLhbvk1DVJKIz7m6HrdKrYqRy8Hgo3TogEo"
);
